### ISSUE TITLE
[Documentation] How to build

### ISSUE THREAD

**Issue by osalbahr** [grsan45/GOOSE#1]
How can I compile and run GOOSE?

**Comment by grsan45** [comment]
This needs to be built on linux or WSL with autotools and qemu installed.

First you'll need an i686-elf compiler, follow this guide: https://wiki.osdev.org/GCC_Cross-Compiler
I'd recommend placing the resulting toolchain in the project directory with the name "i686-elf-cc", this will make configuration easier.

1. To generate the configure script, run `autoreconf --install`
2. To generate the makefile, create a build directory and from within that directory run this command: `../configure --build x86_64-linux-gnu --host i686-elf`
3. To build the OS binary, run `make all -j4` from that build directory

Steps 1 and 2 above only need to be run once unless new files are added

If you're using clion, you can just update your pre-configuration makefile commands (found under makefile settings) to the following, and it will handle the above steps for you: 
```sh
#!/bin/sh
#
# GNU Autotools template, feel free to customize.
#
which autoreconf >/dev/null && autoreconf --install --force --verbose "${PROJECT_DIR:-..}" 2>&1; /bin/sh "${PROJECT_DIR:-..}/configure" --build x86_64-linux-gnu --host i686-elf
```

To run the OS, use the `create-iso.sh` script in the tools/ directory, and run `qemu-system-i386 -serial stdio --cdrom goose.iso`
If you were to run the OS right now, you'd just get a blank screen with a single orange pixel in the top left, but a bunch of serial output in the console. I know this current build system is quite the mess, so let me know if you have any issues or questions.

**Comment by grsan45** [comment]
I'll clean up my prev message and put it in the README tomorrow

**Comment by osalbahr** [comment]
> I'd recommend placing the resulting toolchain in the project directory with the name "i686-elf-cc", this will make configuration easier.

Should I create this directory at the top-level directory of this repo (after cloning it)? Or where would you recommend putting it? Thx!

**Comment by grsan45** [comment]
Yep, I've attached a screenshot of my current directory structure as a guide
![image](https://github.com/grsan45/GOOSE/assets/7763621/0ca8505f-8f5a-4e33-ad71-31b10d08f903)

**Comment by osalbahr** [comment]
Gotcha. The image helps. I’ve not used CLion before, though I’d like to learn how to use it at some point. For now, do I *have to* use CLion?

**Comment by grsan45** [comment]
It's not required, I just use it so the build system is kind of built around its features. However everything can be built and run in a normal terminal

**Comment by osalbahr** [comment]
```console
$ autoreconf --install
configure.ac:23: installing './compile'
configure.ac:26: installing './install-sh'
configure.ac:26: installing './missing'
Makefile.am:2: warning: source file 'src/boot/multiboot.s' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least one source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However, this
automake: behavior may change in a future Automake major version, with object
automake: files being placed in the same subdirectory as the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
Makefile.am:2: warning: source file 'src/boot/boot.s' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am:2: warning: source file 'src/arch/isrs.s' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am:2: warning: source file 'src/arch/gdt.c' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am:2: warning: source file 'src/arch/idt.c' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am:2: warning: source file 'src/display/framebuffer.c' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am:2: warning: source file 'src/string.c' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am:2: warning: source file 'src/arch/memmgt.c' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am:2: warning: source file 'src/io/serial.c' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am:2: warning: source file 'src/kernel.c' is in a subdirectory,
Makefile.am:2: but option 'subdir-objects' is disabled
Makefile.am: installing './depcomp'
```
Can I ignore these warnings?

**Comment by osalbahr** [comment]
Do you know what might be causing this error?
```console
⬢[dracula@toolbox build]$ ../configure --build x86_64-linux-gnu --host i686-elf
checking for i686-elf-gcc... ../i686-elf-cc/bin/i686-elf-gcc
checking whether the C compiler works... no
configure: error: in `/var/home/dracula/git/GOOSE/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
I tried to test `gcc` and got:
```console
⬢[dracula@toolbox build]$ cat test.c
#include<stdio.h>
int main(){puts("Hello, gcc");}
⬢[dracula@toolbox build]$ make test
cc     test.c   -o test
⬢[dracula@toolbox build]$ ./test 
Hello, gcc
```

[config.log](https://github.com/grsan45/GOOSE/files/11990357/config.log)

Edit: looks like i might be missing some files:
```c
configure:2771: checking whether the C compiler works
configure:2793: ../i686-elf-cc/bin/i686-elf-gcc -ffreestanding -nostdlib -gdwarf-4 -m32 -ggdb3 -Wall -Wextra -Werror -std=c17  -nostdlib -lgcc conftest.c  >&5
../configure: line 2795: ../i686-elf-cc/bin/i686-elf-gcc: No such file or directory
configure:2797: $? = 127
configure:2837: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "goose"
| #define PACKAGE_TARNAME "goose"
| #define PACKAGE_VERSION "0.1.0"
| #define PACKAGE_STRING "goose 0.1.0"
| #define PACKAGE_BUGREPORT "http://grsan.xyz"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:2842: error: in `/var/home/dracula/git/GOOSE/build':
configure:2844: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by osalbahr** [comment]
Hmmm that's odd. why does `configure` think I have these files?
```console
$ grep i686-elf-gcc configure
CC=${CC-$srcdir/i686-elf-cc/bin/i686-elf-gcc}
CCAS=${CCAS-$srcdir/i686-elf-cc/bin/i686-elf-gcc}
```

**Comment by grsan45** [comment]
> ```
> ...
> Makefile.am:2: warning: source file 'src/kernel.c' is in a subdirectory,
> Makefile.am:2: but option 'subdir-objects' is disabled
> Makefile.am: installing './depcomp'
> ```
> 
> Can I ignore these warnings?

Yes

As for the other issues you're having,  when you built the cross compiler, you set the TARGET variable to i686-elf right? The resulting binaries should be prefixed with that (i.e i686-elf-gcc, i686-elf-as). You also shouldn't be able to run any of the binaries i686-elf-gcc produces on your system (the compiler checks in ./configure shouldn't suffer from that issue).

**Comment by osalbahr** [comment]
> As for the other issues you're having, when you built the cross compiler, you set the TARGET variable to i686-elf right?

How do I build the cross compiler? So far I only ran the autoreconf and configure commands you gave me.

**Comment by grsan45** [comment]
Use this guide: https://wiki.osdev.org/GCC_Cross-Compiler

I've added some better instructions in the README and an autogen script in my latest commit, should make things a bit easier.

**Comment by osalbahr** [comment]
> Use this guide: https://wiki.osdev.org/GCC_Cross-Compiler
> 
> I've added some better instructions in the README and an autogen script in my latest commit, should make things a bit easier.

Oh wow. That is a pretty ~~long~~ comprehensive guide. I will take a look into it later.
